package fi.oom.vaadin.kalenteri;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Grid;
import com.vaadin.ui.InlineDateField;
import com.vaadin.ui.ListSelect;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.Slider;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class FrontDesign extends VerticalLayout {
	protected MenuBar topMenu;
	protected InlineDateField mainCalendar;
	protected DateField eventDateField;
	protected TextField eventTitleField;
	protected Slider ranniSlider;
	protected ComboBox locationComboBox;
	protected ListSelect participantSelect;
	protected MenuBar crudMenu;
	protected Grid eventsGrid;

	public FrontDesign() {
		Design.read(this);
	}
}
